version: '3'
services:
  exim:
    image: exim
    ports:
      - '145.100.104.117:25:25'
    volumes:
      - $PWD/exim.conf:/etc/exim/exim.conf:ro
      - $PWD/aliases:/etc/mail/aliases:ro
      - $PWD/mailname:/etc/mail/mailname:ro
    entrypoint: ["sh","-c"]
    command: ["chmod 777 /var/mail; adduser -D os3student; /usr/sbin/exim -bdf -q15m"]
  backup:
    image: exim
    ports:
      - '145.100.111.10:25:25'
    volumes:
      - $PWD/exim2.conf:/etc/exim/exim.conf:ro
      - $PWD/aliases:/etc/mail/aliases:ro
      - $PWD/mailname2:/etc/mail/mailname:ro
    entrypoint: ["sh","-c"]
    command: ["chmod 777 /var/mail; adduser -D os3student; /usr/sbin/exim -bdf -q15m"]
