version: '3'
services:
  exim:
    image: exim
    ports:
      - '25:25'
    volumes:
      - $PWD/exim.conf:/etc/exim/exim.conf:ro
      - $PWD/aliases:/etc/mail/aliases:ro
      - $PWD/mailname:/etc/mail/mailname:ro
